---
# This is a inner loop task that is called by the outer loop task: ensure all operators are up
- name: verify operator status
  block:
    - name: wait for operator {{ operator_name }} available status to be True
      until: _operator_status.stdout.find("True") != -1
      retries: 60
      delay: 30
      shell: >
        oc get co {{ operator_name }} --no-headers|awk '/True/ {print $3}'| grep -o True
      register: _operator_status
      changed_when: False
      environment:
        KUBECONFIG: "{{ ocp_cluster_admin_kubeconfig }}"
      become: no
  rescue:
    - debug:
        msg:
          - "The operator {{ operator_name }} status did not change from {{ _operator_status.stdout }} to True."
          - "You can verify the status of the operators with 'oc get clusteroperators'."
          - "Remove this attempt before running the installer again."
          - "Run './qubinode-installer -p {{ ocp4_okd4 }}'"
    - name: fail if cluster deployment was unsuccessful
      fail:
        msg: The cluster deployment was unsuccessfull
  tags: [bootstrap, postinstall, check_cluster_status, complete_install ]
