---
- name: does the openshift-storage namespace exist
  shell: "{{ ocp_client_cmd }} get all -n openshift-storage"
  register: openshift_storage_namespace
  ignore_errors: yes
  changed_when: False
  environment:
    KUBECONFIG: "{{ ocp_cluster_admin_kubeconfig }}"

- name: check for the local storage operator pods
  shell: "{{ ocp_client_cmd }} -n openshift-storage get pods|grep Running"
  register: openshift_storage_operator_pods
  ignore_errors: yes
  changed_when: False
  environment:
    KUBECONFIG: "{{ ocp_cluster_admin_kubeconfig }}"


- name: check if the local storage operator is available
  shell: "{{ ocp_client_cmd }} get csvs -n openshift-storage | grep Succeeded"
  register: openshift_storage_operator_status
  ignore_errors: yes
  changed_when: False
  environment:
    KUBECONFIG: "{{ ocp_cluster_admin_kubeconfig }}"

- name: set the status of the openshift-storage namespace
  set_fact:
    namespace_exist: "{{ false if 'No resources found' in openshift_storage_namespace.stderr else true }}"

- name: set the status of the openshift-storage pods
  set_fact:
    openshift_storage_operator_pods_exist: "{{ true if openshift_storage_operator_pods.rc == 0 else false }}"

- name: set the status of the openshift-storage operator
  set_fact:
    openshift_storage_operator_exist: "{{ true if openshift_storage_operator_status.rc == 0 else false }}"
