---
- name: does the openshift-storage namespace exist
  shell: /usr/local/bin/oc get all -n openshift-storage
  register: openshift_storage_namespace
  ignore_errors: yes
  changed_when: False
  environment:
    KUBECONFIG: "{{ openshift_install_dir }}/auth/kubeconfig"

- name: check for the local storage operator pods
  shell: /usr/local/bin/oc -n openshift-storage get pods|grep Running
  register: openshift_storage_operator_pods
  ignore_errors: yes
  changed_when: False
  environment:
    KUBECONFIG: "{{ openshift_install_dir }}/auth/kubeconfig"


- name: check if the local storage operator is available
  shell: /usr/local/bin/oc get csvs -n openshift-storage | grep Succeeded
  register: openshift_storage_operator_status
  ignore_errors: yes
  changed_when: False
  environment:
    KUBECONFIG: "{{ openshift_install_dir }}/auth/kubeconfig"

- name: set the status of the openshift-storage namespace
  set_fact:
    namespace_exist: "{{ false if 'No resources found' in openshift_storage_namespace.stderr else true }}"

- name: set the status of the openshift-storage pods
  set_fact:
    openshift_storage_operator_pods_exist: "{{ true if openshift_storage_operator_pods.rc == 0 else false }}"

- name: set the status of the openshift-storage operator
  set_fact:
    openshift_storage_operator_exist: "{{ true if openshift_storage_operator_status.rc == 0 else false }}"
