---
- name: Get the cluster API url
  command: "{{ ocp_client_cmd }} whoami --show-server"
  register: api_url
  tags: [ smoketest, smoketest-verify, smoketest-app]

- name: Get the webconsole url
  command: "{{ ocp_client_cmd }}" whoami --show-console
  register: routeconsole
  tags: [ smoketest, smoketest-verify, smoketest-app ]

- name: Set webconsole url
  set_fact:
    webconsole: "{{ routeconsole.stdout }}"
  tags: [ smoketest, smoketest-verify, smoketest-app ]

- name: verify dns and cluster
  tags: [ smoketest, smoketest-verify ]
  block:
    - name: Check DNS webconsole
      command: nslookup "{{ webconsole | urlsplit('hostname') }}"
      register: checkdnswebconsole
      changed_when: false
      retries: 15
      until: checkdnswebconsole is succeeded
      delay: 30

    - name: Check DNS API
      command: nslookup "{{ api_url.stdout | trim | urlsplit('hostname') }}"
      register: checkdnsapi
      changed_when: false

    - name: Webconsole
      uri:
        url: "{{ webconsole }}"
        validate_certs: false
      register: testwebconsole
      retries: 5
      until: testwebconsole is succeeded
      delay: 60

    - name: Cluster-info
      command: "{{ ocp_client_cmd }}" cluster-info
      register: clusterinfor
      changed_when: false

- name: test deploying a PHP LAMP Stack
  tags: [ smoketest, smoketest-app ]
  block:

    - name: Create project
      command: "{{ ocp_client_cmd }}" new-project postflightcheck
      register: newproject

    - name: New-app
      command: "{{ ocp_client_cmd }}" new-app cakephp-mysql-persistent -n postflightcheck
      register: newapp

    - name: Wait for mysql
      command: timeout 600 "{{ ocp_client_cmd }}" rollout status dc/mysql -w -n postflightcheck
      register: mysqlw
      changed_when: false

    - name: Wait for php
      command: timeout 600 "{{ ocp_client_cmd }}" rollout status dc/cakephp-mysql-persistent -w -n postflightcheck
      register: phpw
      changed_when: false
      retries: 2
      delay: 60
      until: phpw is succeeded

    - name: Get route
      command: >-
        "{{ ocp_client_cmd }}" get route
        -l template=cakephp-mysql-persistent
        --no-headers
        -o json
        -n postflightcheck
      register: getroute
      changed_when: false
      retries: 10
      delay: 5
      until: getroute is succeeded

    - name: Test that route is reachable
      uri:
        url: "http://{{ getroute.stdout|from_json|json_query('items[0].spec.host') }}"
      register: testroute
      retries: 15
      delay: 5
      until: testroute is succeeded

  always:
    - name: Delete project
      command: "{{ ocp_client_cmd }}" delete project postflightcheck
      become: no
      ignore_errors: yes

    - name: Switch back to default project
      command: "{{ ocp_client_cmd }}" project default
      become: no
      ignore_errors: yes

- name: Report on smoketest results
  tags: [ smoketest, smoketest-app, smoketest-verify ]
  block:
    - name: SMOKE TEST RESULTS
      debug:
        msg: "{{ item }}"
      loop:
        - "user.info: "
        - "user.info: Post Flight Check"
        - "user.info: DNS Web Console ............... {{ 'OK' if checkdnswebconsole is defined and checkdnswebconsole.rc == 0 else 'FAIL' }}"
        - "user.info: DNS API ....................... {{ 'OK' if checkdnsapi is defined and checkdnsapi.rc == 0 else 'FAIL' }}"
        - "user.info: Web console ................... {{ 'OK' if testwebconsole is defined and testwebconsole is succeeded else 'FAIL' }}"
        - "user.info: API ........................... {{ 'OK' if clusterinfor is defined and clusterinfor.rc == 0 else 'FAIL' }}"
        - "user.info: Create Project with PV ........ {{ 'OK' if newproject is defined and newproject.rc == 0 else 'FAIL' }}"
        - "user.info: App deployed .................. {{ 'OK' if phpw is defined and phpw.rc == 0 and mysqlw.rc == 0 else 'FAIL' }}"
        - "user.info: Route ......................... {{ 'OK' if testroute  is defined and testroute is succeeded else 'FAIL' }}"

  rescue:
    - name: Smoke test failed
      debug:
        msg: 'Aborting smoke test as a result of a failure when deploying the php lamp stack'


#- name: set cluster deployed message
#  set_fact:
#    cluster_deployed_msg: "{{ 'deployed' if checkdnsapi.rc == 0 and testwebconsole.status == 200 and clusterinfor.rc == 0 and newproject.rc == 0 else 'notdeployed' }}"
#  tags: [ smoketest, smoketest-app, smoketest-verify, verify-cluster ]
#
#- name: cluster deployment complete
#  debug:
#     msg:
#       - "*****************************"
#       - " Cluster deployment complete "
#       - "*****************************"
#       - "checkdnsapi: {{ checkdnsapi.rc }}"
#       - "testwebconsole: {{ testwebconsole.status }}"
#       - "clusterinfor: {{ clusterinfor.rc }}"
#       - "newproject: {{ newproject.rc }}"
#  tags: verify-cluster
#


#- name: Ensure web console is known
#  tags: [ smoketest, smoketest-verify ]
#  block:
#    - name: Get console route
#      command: oc get route -n openshift-console console -o json
#      register: routeconsole
#      retries: 10
#      delay: 30
#      until: routeconsole is succeeded
#      ignore_errors: true
#      tags: [ smoketest, smoketest-verify ]
#
#    - name: Set webconsole address
#      set_fact:
#        webconsole: "http://{{ routeconsole.stdout | from_json | json_query('spec.host') }}"
#      when: routeconsole is succeeded
#      tags: [ smoketest, smoketest-verify ]
#  become: no