#!/bin/bash

# Add a new worker node to the clsuter

node_name=$1
WAIT_TIME=20

if [ "$1" != "" ]
then
    LASP_TIME=0
    until oc get nodes | grep $node_name || [ $LASP_TIME -eq $WAIT_TIME ]
    do
        oc get csr -ojson |\
            jq -r '.items[] |\ 
            select(.status == {} ) |\ 
            .metadata.name'|\
            xargs oc adm certificate approve
        oc get nodes > /dev/null
        sleep $(( LASP_TIME++ ))
    done
else
    echo "You must a ocp node name"
    exit 1
fi

exit 0
